Repository near/NEPs, pull requests merged in 2022-10, with the labels that each got.

#132 recalibrate inflation
  specs/Economics/README.md
Labels: WG-protocol

#364 NEP-364: Efficient signature verification host functions
  neps/nep-0364.md
Labels: A-runtime, WG-protocol, S-approved

#411 Replace a noun with its verb
  specs/Proposals/0008-transaction-refactoring.md
Labels: WG-unknown

#401 fix: Corrected the notes for the "Reference Implementation" section
  nep-0000-template.md
Labels: documentation, WG-unknown

#408 NEP-408: Injected Wallet API
  specs/Standards/Wallets/InjectedWallets.md
Labels: WG-wallet-standards, S-approved, NEP
