Repository near/NEPs, pull requests merged in 2022-09, with the labels that each got.

#264 Utilization of unspent gas for promise function calls
  specs/Proposals/0264-promise_gas_ratio.md
Labels: A-runtime, T-protocol

#368 NEP-368: Bridge Wallet Standard
  specs/Standards/Wallets/BridgeWallets.md
Labels: T-wallet-standards

#241 NEPs on how to split states of shards for resharding
  specs/Proposals/0040-split-states.md
Labels: T-protocol

#398 a `error` added
  specs/RuntimeSpec/Transactions.md
Labels: WG-unknown

#394 Updating NEP-141 authors
  neps/nep-0141.md
Labels: documentation, WG-contract-standards

#395 Update Architecture.md
  specs/Architecture.md
Labels: documentation, WG-protocol

#396 Update Architecture.md
  specs/Architecture.md
Labels: documentation, WG-protocol

#388 Fix some formatting issues in Consensus.md
  specs/ChainSpec/Consensus.md
Labels: documentation, WG-protocol
