Repository near/NEPs, pull requests merged in 2022-12, with the labels that each got.

#439 chore: reformat transaction validation section
  specs/RuntimeSpec/Transactions.md
Labels: WG-protocol, S-draft/needs-moderator-review, A-Nomicon-Changes

#203 fixes min/max typo and indented code blocks
  specs/Standards/Tokens/FungibleToken/Core.md
Labels: WG-contract-standards, S-approved, A-NEP-GrammarFix

#238 standards/NFT: previous_owner_id
  specs/Standards/Tokens/NonFungibleToken/Core.md
Labels: WG-contract-standards

#337 Update Transactions.md
  specs/ChainSpec/Transactions.md
Labels: help wanted, WG-protocol, S-approved, A-Nomicon-Changes

#361 Fixed Error in Access Key Docs
  specs/DataStructures/AccessKey.md
Labels: WG-unknown

#373 Nits on nep template
  nep-0000-template.md
Labels: WG-unknown, S-approved, A-Housekeeping
